# site settings
title: chrisdill.github.io
email: chris.rj.dill@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chris's personal portfolio and blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chrisdill
linkedin_username: chris-dill
google_analytics: UA-120787474-1

# build settings
markdown: kramdown

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - build.bat
  - build.sh
