# site settings
title: chrisdill.github.io
name: Chris Dill
description: Developing software, games and other fun things!
keywords: Chris, Games, Web, Software, Developer, Computer Science

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

logo: /assets/images/logo.webp
copyright: 2020 Chris Dill

email: chris.rj.dill@gmail.com
github: https://github.com/ChrisDill
linkedin: https://www.linkedin.com/in/chris-dill/
rss: feed.xml
google_analytics: UA-118914878-1

# build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/

include: ['_pages']

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md

plugins:
  - jekyll-feed
