# site settings
title: chrisdill.github.io
name: Chris Dill
description: Developing software, games and other fun things!
keywords: Chris, Games, Web, Software, Developer, Computer Science

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

avatar: /assets/chris-logo.png
copyright: Chris Dill 2020

email: chris.rj.dill@gmail.com
github_username: ChrisDill
linkedin_username: chris-dill
rss: feed.xml
google_analytics: UA-118914878-1

# build settings
markdown: kramdown
highlighter: rouge

include: ['_pages']

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - build.bat
  - build.sh
  - README.md

plugins:
  - jekyll-feed
