# site settings
title: chrisdill.github.io
email: chrisdude134@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Testing site.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chrisdill
linkedin_username: chris-dill
google_analytics: UA-120787474-1

# build settings
markdown: kramdown
#theme: minima

